server:
  port: 8888

spring:
  artemis:
    embedded:
      enabled: false
    host: 172.16.42.237
    port: 61616
    user: admim
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/project_record?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: longdaye
    driver-class-name: com.mysql.cj.jdbc.Driver


